// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

/*
Package game is a generated protocol buffer package.

It is generated from these files:
	game.proto

It has these top-level messages:
	CSMSG
	SCMSG
	MSG_LOGIN_CS
	MSG_LOGIN_SC
*/
package game

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_MSG_ZERO_PLACEHOLDER MessageType = 0
	MessageType_MSG_ERROR            MessageType = 1
	MessageType_MSG_PING             MessageType = 2
	MessageType_MSG_LOGIN            MessageType = 3
	MessageType_MSG_KICKOUT          MessageType = 4
)

var MessageType_name = map[int32]string{
	0: "MSG_ZERO_PLACEHOLDER",
	1: "MSG_ERROR",
	2: "MSG_PING",
	3: "MSG_LOGIN",
	4: "MSG_KICKOUT",
}
var MessageType_value = map[string]int32{
	"MSG_ZERO_PLACEHOLDER": 0,
	"MSG_ERROR":            1,
	"MSG_PING":             2,
	"MSG_LOGIN":            3,
	"MSG_KICKOUT":          4,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CSMSG struct {
	Msg  MessageType `protobuf:"varint,1,opt,name=msg,enum=game.MessageType" json:"msg,omitempty"`
	Body []byte      `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *CSMSG) Reset()                    { *m = CSMSG{} }
func (m *CSMSG) String() string            { return proto.CompactTextString(m) }
func (*CSMSG) ProtoMessage()               {}
func (*CSMSG) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CSMSG) GetMsg() MessageType {
	if m != nil {
		return m.Msg
	}
	return MessageType_MSG_ZERO_PLACEHOLDER
}

func (m *CSMSG) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type SCMSG struct {
	Msg     MessageType `protobuf:"varint,1,opt,name=msg,enum=game.MessageType" json:"msg,omitempty"`
	RetCode int32       `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Body    []byte      `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *SCMSG) Reset()                    { *m = SCMSG{} }
func (m *SCMSG) String() string            { return proto.CompactTextString(m) }
func (*SCMSG) ProtoMessage()               {}
func (*SCMSG) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SCMSG) GetMsg() MessageType {
	if m != nil {
		return m.Msg
	}
	return MessageType_MSG_ZERO_PLACEHOLDER
}

func (m *SCMSG) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *SCMSG) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type MSG_LOGIN_CS struct {
	RoleId int64 `protobuf:"varint,1,opt,name=role_id,json=roleId" json:"role_id,omitempty"`
}

func (m *MSG_LOGIN_CS) Reset()                    { *m = MSG_LOGIN_CS{} }
func (m *MSG_LOGIN_CS) String() string            { return proto.CompactTextString(m) }
func (*MSG_LOGIN_CS) ProtoMessage()               {}
func (*MSG_LOGIN_CS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MSG_LOGIN_CS) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

type MSG_LOGIN_SC struct {
	RetCode int32  `protobuf:"varint,1,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	RetMsg  string `protobuf:"bytes,2,opt,name=ret_msg,json=retMsg" json:"ret_msg,omitempty"`
}

func (m *MSG_LOGIN_SC) Reset()                    { *m = MSG_LOGIN_SC{} }
func (m *MSG_LOGIN_SC) String() string            { return proto.CompactTextString(m) }
func (*MSG_LOGIN_SC) ProtoMessage()               {}
func (*MSG_LOGIN_SC) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MSG_LOGIN_SC) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *MSG_LOGIN_SC) GetRetMsg() string {
	if m != nil {
		return m.RetMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*CSMSG)(nil), "game.CSMSG")
	proto.RegisterType((*SCMSG)(nil), "game.SCMSG")
	proto.RegisterType((*MSG_LOGIN_CS)(nil), "game.MSG_LOGIN_CS")
	proto.RegisterType((*MSG_LOGIN_SC)(nil), "game.MSG_LOGIN_SC")
	proto.RegisterEnum("game.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("game.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x4d, 0xf3, 0xa7, 0xed, 0x34, 0x6a, 0x5c, 0x04, 0xe3, 0xad, 0xc4, 0x83, 0xc5, 0x43,
	0x0f, 0xfa, 0x05, 0xd4, 0x35, 0xc4, 0xd0, 0xa4, 0x29, 0xbb, 0xf5, 0xa2, 0x87, 0xa5, 0x75, 0x87,
	0x20, 0x58, 0xb6, 0x24, 0xb9, 0xf4, 0xdb, 0xcb, 0x2c, 0x28, 0xe9, 0xcd, 0xdb, 0x3c, 0xde, 0xe3,
	0xf7, 0x1e, 0x03, 0x50, 0x6f, 0x76, 0x38, 0xdf, 0x37, 0xa6, 0x33, 0xcc, 0xa3, 0x3b, 0x79, 0x04,
	0x9f, 0xcb, 0x52, 0x66, 0xec, 0x06, 0xdc, 0x5d, 0x5b, 0xc7, 0xce, 0xd4, 0x99, 0x9d, 0xdd, 0x5f,
	0xcc, 0x6d, 0xb0, 0xc4, 0xb6, 0xdd, 0xd4, 0xb8, 0x3e, 0xec, 0x51, 0x90, 0xcb, 0x18, 0x78, 0x5b,
	0xa3, 0x0f, 0xf1, 0x60, 0xea, 0xcc, 0x42, 0x61, 0xef, 0xe4, 0x03, 0x7c, 0xc9, 0xff, 0x4d, 0xb8,
	0x86, 0x51, 0x83, 0x9d, 0xfa, 0x34, 0x1a, 0x2d, 0xc5, 0x17, 0xc3, 0x06, 0x3b, 0x6e, 0x34, 0xfe,
	0xc1, 0xdd, 0x1e, 0xfc, 0x16, 0xc2, 0x52, 0x66, 0xaa, 0xa8, 0xb2, 0x7c, 0xa9, 0xb8, 0x64, 0x57,
	0x30, 0x6c, 0xcc, 0x37, 0xaa, 0x2f, 0x6d, 0x7b, 0x5c, 0x11, 0x90, 0xcc, 0x75, 0xf2, 0xdc, 0x0f,
	0x4a, 0x7e, 0xd4, 0xe3, 0x1c, 0xf7, 0x10, 0x03, 0x3b, 0x45, 0x5b, 0x69, 0xc1, 0x58, 0x04, 0x0d,
	0x76, 0x65, 0x5b, 0xdf, 0x69, 0x98, 0xf4, 0xf6, 0xb2, 0x18, 0x2e, 0x09, 0xf9, 0x9e, 0x8a, 0x4a,
	0xad, 0x8a, 0x27, 0x9e, 0xbe, 0x56, 0xc5, 0x4b, 0x2a, 0xa2, 0x13, 0x76, 0x0a, 0x63, 0x72, 0x52,
	0x21, 0x2a, 0x11, 0x39, 0x2c, 0x84, 0x11, 0xc9, 0x55, 0xbe, 0xcc, 0xa2, 0xc1, 0xaf, 0x69, 0x97,
	0x44, 0x2e, 0x3b, 0x87, 0x09, 0xc9, 0x45, 0xce, 0x17, 0xd5, 0xdb, 0x3a, 0xf2, 0xb6, 0x81, 0x7d,
	0xff, 0xc3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xf8, 0x93, 0xfb, 0x8c, 0x01, 0x00, 0x00,
}
